name: Fetch GitHub Issues

on:
  push:
    branches:
      - main

jobs:
  fetch-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Issues
        run: |
        
          API_DATA1=$(curl -X GET "https://api.github.com/repos/ARK-Builders/website/issues")
          API_DATA2=$(curl -X GET "https://api.github.com/repos/ARK-Builders/arklib/issues")
          API_DATA3=$(curl -X GET "https://api.github.com/repos/ARK-Builders/arklib-android/issues")
          
          # Use JavaScript to parse the JSON arrays and combine them
          combined_json=$(node -e "const combined = [...${API_DATA1}, ...${API_DATA2}]; const combinedF = [...combined, ...${API_DATA3}]; ")

          
          echo "$combined_json" > test.json
          
          
      - name: Push into Git
        run: |-
          git config --global user.email "moeenranjha01@gmail.com"
          git config --global user.name "Moeenahamd"
          git add test.json
          git commit -m "Automated update of rate"
          git push
      
        
