name: Fetch GitHub Issues

on:
  push:
    branches:
      - main

jobs:
  fetch-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Issues
        run: |
          # Replace these placeholders with your GitHub username, repository, and optional personal access token
          GITHUB_USERNAME=Moeenahamd
          GITHUB_REPO=moeenahamd.github.io
          GITHUB_TOKEN=${{secrets.PETOKEN}}

          # Create a variable for the GitHub API URL
          GITHUB_API_URL="https://api.github.com/repos/$GITHUB_USERNAME/$GITHUB_REPO/issues"
          
          GITHUB_API_URL2="https://api.github.com/repos/MaxMelcher/profile-darkmode/issues"

          # Fetch issues from the repository
          if [ -n "$GITHUB_TOKEN" ]; then
            API_DATA1=$(curl -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "$GITHUB_API_URL")
                 
            echo "$API_DATA" > test1.json
            
            API_DATA2=$(curl -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "$GITHUB_API_URL2")
                 
            echo "$API_DATA2" > test2.json
            
            json1=$(cat test1.json)
            json2=$(cat test2.json)

          # Combine the JSON arrays using JavaScript
          #  combined_json=$(node -e "const arr1 = $json1; const arr2 = $json2; const combined = arr1.concat(arr2); console.log(JSON.stringify(combined));" > combined.json)

            
          else
            curl -H "Accept: application/vnd.github.v3+json" "$GITHUB_API_URL" --output fiat-rates.json
          fi
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Execute JavaScript
        run: |
          # Write your JavaScript code here
          console.log(json1,json2);
      - name: Push into Git
        run: |-
          git config --global user.email "moeenranjha01@gmail.com"
          git config --global user.name "Moeenahamd"
          # git add combined.json
          # git commit -m "Automated update of rate"
          # git push
        
