name: JavaScript Example

on:
  push:
    branches:
      - main

jobs:
  run_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Execute JavaScript
        run: |
          echo "Running JavaScript code"
          const num1 = 5;
          const num2 = 7;
          const sum = num1 + num2;
          echo "The sum of ${num1} and ${num2} is ${sum}"
