name: Fetch GitHub Issues

on:
  push:
    branches:
      - main

jobs:
  fetch-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Issues
        run: |
          # Replace these placeholders with your GitHub username, repository, and optional personal access token
          GITHUB_USERNAME=Moeenahamd
          GITHUB_REPO=moeenahamd.github.io
          GITHUB_TOKEN=${{secrets.PETOKEN}}

          # Create a variable for the GitHub API URL
          GITHUB_API_URL="https://api.github.com/repos/$GITHUB_USERNAME/$GITHUB_REPO/issues"
          
          GITHUB_API_URL2="https://api.github.com/repos/MaxMelcher/profile-darkmode/issues"

          # Fetch issues from the repository
          if [ -n "$GITHUB_TOKEN" ]; then
            API_DATA1=$(curl -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "$GITHUB_API_URL")
                 
            API_DATA2=$(curl -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "$GITHUB_API_URL2")
                 
          combined_array=("${API_DATA1[@]}","${API_DATA2[@]}")
          echo "$API_DATA1" > test.json
          
          # Use JavaScript to parse the JSON arrays and combine them
          combined_json=$(node -e "const arr1 = ${API_DATA1}; const arr2 = ${API_DATA1}; const combined = [...arr1, ...arr2]; console.log(JSON.stringify(combined));")

          # Set the output variable with the concatenated array
          echo "::set-output name=concatenated_array::${combined_array[@]}"
          
            
          else
            curl -H "Accept: application/vnd.github.v3+json" "$GITHUB_API_URL" --output fiat-rates.json
          fi
          
      - name: Push into Git
        run: |-
          git config --global user.email "moeenranjha01@gmail.com"
          git config --global user.name "Moeenahamd"
          git add test.json
          git commit -m "Automated update of rate"
          git push
      
        
