name: JavaScript Concatenate Arrays

on:
  push:
    branches:
      - main

jobs:
  run_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Execute JavaScript
        id: javascript
        run: |
          echo "Running JavaScript code"
          # Define two example arrays
          array1=("apple" "banana" "cherry")
          array2=("date" "fig" "grape")

          # Use concat to combine the arrays
          combined_array=("${array1[@]}" "${array2[@]}")

          # Set the output variable with the concatenated array
          echo "::set-output name=concatenated_array::${combined_array[@]}"
          
      - name: Display Result
        run: |
          # Display the concatenated array
          echo "Concatenated Array: ${{ steps.javascript.outputs.concatenated_array }}"
