name: Return Data from JavaScript Function

on:
  push:
    branches:
      - main

jobs:
  run_my_function:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run JavaScript Function and Set Output
        id: myfunction
        run: |
          const myFunction = require('./myFunction');
          const data = myFunction.getData();
          console.log(data);
          console.log(`::set-output name=data::${data}`)

      - name: Use the Output Data
        run: |
          echo "The data returned by the JavaScript function: ${{ steps.myfunction.outputs.data }}"
