name: JavaScript Example

on:
  push:
    branches:
      - main

jobs:
  run_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Execute JavaScript
        id: javascript
        run: |
          echo "Running JavaScript code"
          num1=5
          num2=7
          sum=$((num1 + num2))
          echo "::set-output name=sum::$sum"
          
      - name: Display Result
        run: |
          echo "The sum of ${{ steps.javascript.outputs.sum }}"
