name: Fetch GitHub Issues

on:
  push:
    branches:
      - main

jobs:
  fetch-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Issues
        run: |
          # Replace these placeholders with your GitHub username, repository, and optional personal access token
          GITHUB_USERNAME=Moeenahamd
          GITHUB_REPO=moeenahamd.github.io
          GITHUB_TOKEN=${{secrets.PETOKEN}}

          # Create a variable for the GitHub API URL
          GITHUB_API_URL="https://api.github.com/repos/$GITHUB_USERNAME/$GITHUB_REPO/issues"

          # Fetch issues from the repository
          if [ -n "$GITHUB_TOKEN" ]; then
            curl -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "$GITHUB_API_URL" --output test.json
          else
            curl -H "Accept: application/vnd.github.v3+json" "$GITHUB_API_URL" --output fiat-rates.json
          fi
          
      - name: Push into Git
        run: |-
          git config --global user.email "bot@ark-builders.dev"
          git config --global user.name "ARK Builders Bot"
          git add fiat-rates.json
          git add crypto-rates.json
          git commit -m "Automated update of rates"
          git push
        
